// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layer/bridge/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// Percentage of stake to slash for oracle attestation violations (as decimal)
	AttestSlashPercentage cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=attest_slash_percentage,json=attestSlashPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"attest_slash_percentage" yaml:"attest_slash_percentage"`
	// Rate limit window in milliseconds for attestation submissions
	AttestRateLimitWindow uint64 `protobuf:"varint,2,opt,name=attest_rate_limit_window,json=attestRateLimitWindow,proto3" json:"attest_rate_limit_window,omitempty" yaml:"attest_rate_limit_window"`
	// Percentage of stake to slash for validator set signature violations (as decimal)
	ValsetSlashPercentage cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=valset_slash_percentage,json=valsetSlashPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"valset_slash_percentage" yaml:"valset_slash_percentage"`
	// Rate limit window in milliseconds for valset signature submissions
	ValsetRateLimitWindow uint64 `protobuf:"varint,4,opt,name=valset_rate_limit_window,json=valsetRateLimitWindow,proto3" json:"valset_rate_limit_window,omitempty" yaml:"valset_rate_limit_window"`
	// Timestamp cutoff before which no attestations or valset signatures can be slashed
	AttestPenaltyTimeCutoff uint64 `protobuf:"varint,5,opt,name=attest_penalty_time_cutoff,json=attestPenaltyTimeCutoff,proto3" json:"attest_penalty_time_cutoff,omitempty" yaml:"attest_penalty_time_cutoff"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f88be139eaafb360, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAttestRateLimitWindow() uint64 {
	if m != nil {
		return m.AttestRateLimitWindow
	}
	return 0
}

func (m *Params) GetValsetRateLimitWindow() uint64 {
	if m != nil {
		return m.ValsetRateLimitWindow
	}
	return 0
}

func (m *Params) GetAttestPenaltyTimeCutoff() uint64 {
	if m != nil {
		return m.AttestPenaltyTimeCutoff
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "layer.bridge.Params")
}

func init() { proto.RegisterFile("layer/bridge/params.proto", fileDescriptor_f88be139eaafb360) }

var fileDescriptor_f88be139eaafb360 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x6a, 0xdb, 0x40,
	0x1c, 0xc7, 0xa5, 0x56, 0x35, 0x54, 0x74, 0x32, 0x2d, 0x95, 0x5d, 0x90, 0x5c, 0x95, 0x82, 0x3b,
	0x58, 0x1a, 0xba, 0x79, 0xb4, 0x3d, 0x7a, 0x30, 0x76, 0xa1, 0x10, 0x02, 0xe2, 0x24, 0xff, 0x2c,
	0x1f, 0xb9, 0xf3, 0x09, 0xdd, 0x39, 0x8e, 0x9e, 0x21, 0x4b, 0xc6, 0x8c, 0x79, 0x88, 0x3c, 0x84,
	0xc9, 0x64, 0x32, 0x85, 0x0c, 0x22, 0xd8, 0x6f, 0xe0, 0x27, 0x08, 0xbe, 0x93, 0x03, 0xfe, 0xb7,
	0x64, 0x93, 0xf4, 0xfd, 0xf2, 0xd1, 0x7d, 0x8e, 0xaf, 0x59, 0x21, 0x28, 0x83, 0xd4, 0x0f, 0x53,
	0x3c, 0x8c, 0xc1, 0x4f, 0x50, 0x8a, 0x28, 0xf7, 0x92, 0x94, 0x09, 0x56, 0xfe, 0x22, 0x23, 0x4f,
	0x45, 0xd5, 0xaf, 0x31, 0x8b, 0x99, 0x0c, 0xfc, 0xcd, 0x93, 0xea, 0x54, 0x2b, 0x11, 0xe3, 0x94,
	0xf1, 0x40, 0x05, 0xea, 0x45, 0x45, 0xee, 0x83, 0x61, 0x96, 0x7a, 0x92, 0x57, 0xbe, 0xd6, 0xcd,
	0xef, 0x48, 0x08, 0xe0, 0x22, 0xe0, 0x04, 0xf1, 0x71, 0x90, 0x40, 0x1a, 0xc1, 0x44, 0xa0, 0x18,
	0x2c, 0xbd, 0xa6, 0xd7, 0x3f, 0xb7, 0x06, 0xf3, 0xdc, 0xd1, 0x9e, 0x73, 0xe7, 0x87, 0x42, 0xf0,
	0xe1, 0x85, 0x87, 0x99, 0x4f, 0x91, 0x18, 0x7b, 0x5d, 0x88, 0x51, 0x94, 0x75, 0x20, 0x5a, 0xe7,
	0x8e, 0x9d, 0x21, 0x4a, 0x9a, 0xee, 0x09, 0x96, 0xfb, 0x78, 0xdf, 0x30, 0x8b, 0x33, 0x74, 0x20,
	0xea, 0x7f, 0x53, 0xbd, 0xc1, 0xa6, 0xd6, 0x7b, 0x6b, 0x95, 0xcf, 0x4d, 0xab, 0x00, 0xa4, 0x48,
	0x40, 0x40, 0x30, 0xc5, 0x22, 0x98, 0xe1, 0xc9, 0x90, 0xcd, 0xac, 0x0f, 0x35, 0xbd, 0x6e, 0xb4,
	0x7e, 0xad, 0x73, 0xc7, 0xd9, 0xf9, 0xd5, 0x41, 0xd3, 0xdd, 0xd2, 0xfb, 0x48, 0x40, 0x77, 0x13,
	0xfc, 0x97, 0xdf, 0xa5, 0xeb, 0x25, 0x22, 0x1c, 0x8e, 0xb8, 0x7e, 0x7c, 0x87, 0xeb, 0x09, 0xd6,
	0x81, 0xab, 0xea, 0x1d, 0x71, 0x2d, 0x00, 0x87, 0xae, 0xc6, 0xbe, 0xeb, 0xa9, 0xa6, 0xbb, 0xa5,
	0xef, 0xbb, 0x86, 0x66, 0xb5, 0xb8, 0x9f, 0x04, 0x26, 0x88, 0x88, 0x2c, 0x10, 0x98, 0x42, 0x10,
	0x4d, 0x05, 0x1b, 0x8d, 0xac, 0x4f, 0x92, 0xff, 0x7b, 0x9d, 0x3b, 0x3f, 0x77, 0xee, 0xf2, 0x48,
	0xd7, 0xed, 0x17, 0xfb, 0xe8, 0xa9, 0xec, 0x1f, 0xa6, 0xd0, 0x96, 0x49, 0xd3, 0xb8, 0xbd, 0x73,
	0xb4, 0x56, 0x7b, 0xbe, 0xb4, 0xf5, 0xc5, 0xd2, 0xd6, 0x5f, 0x96, 0xb6, 0x7e, 0xb3, 0xb2, 0xb5,
	0xc5, 0xca, 0xd6, 0x9e, 0x56, 0xb6, 0x76, 0xf6, 0x27, 0xc6, 0x62, 0x3c, 0x0d, 0xbd, 0x88, 0x51,
	0x5f, 0x00, 0x21, 0x2c, 0x6d, 0x60, 0xe6, 0xab, 0x55, 0x5f, 0x6d, 0x77, 0x2d, 0xb2, 0x04, 0x78,
	0x58, 0x92, 0xc3, 0xfc, 0xfb, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x51, 0x13, 0xb8, 0x1d, 0xf4, 0x02,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AttestPenaltyTimeCutoff != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AttestPenaltyTimeCutoff))
		i--
		dAtA[i] = 0x28
	}
	if m.ValsetRateLimitWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ValsetRateLimitWindow))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.ValsetSlashPercentage.Size()
		i -= size
		if _, err := m.ValsetSlashPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.AttestRateLimitWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AttestRateLimitWindow))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.AttestSlashPercentage.Size()
		i -= size
		if _, err := m.AttestSlashPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.AttestSlashPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.AttestRateLimitWindow != 0 {
		n += 1 + sovParams(uint64(m.AttestRateLimitWindow))
	}
	l = m.ValsetSlashPercentage.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.ValsetRateLimitWindow != 0 {
		n += 1 + sovParams(uint64(m.ValsetRateLimitWindow))
	}
	if m.AttestPenaltyTimeCutoff != 0 {
		n += 1 + sovParams(uint64(m.AttestPenaltyTimeCutoff))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestSlashPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AttestSlashPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestRateLimitWindow", wireType)
			}
			m.AttestRateLimitWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestRateLimitWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetSlashPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValsetSlashPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetRateLimitWindow", wireType)
			}
			m.ValsetRateLimitWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValsetRateLimitWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestPenaltyTimeCutoff", wireType)
			}
			m.AttestPenaltyTimeCutoff = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestPenaltyTimeCutoff |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
