event_types:
  - alert_name: "NEW_DISPUTE"
    alert_type: "new_dispute"
    query: "new_dispute.reporter EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "DISPUTE_ROUND_ADDED"
    alert_type: "added_dispute_round"
    query: "added_dispute_round.dispute_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "DISPUTE_EXECUTED"
    alert_type: "dispute_executed"
    query: "dispute_executed.dispute_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "DEPOSIT_CLAIMED"
    alert_type: "deposit_claimed"
    query: "deposit_claimed.deposit_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "WITHDRAWAL_INITIATED"
    alert_type: "tokens_withdrawn"
    query: "tokens_withdrawn.withdraw_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "TIP_ADDED"
    alert_type: "tip_added"
    query: "tip_added.query_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "AGGREGATE_REPORT"
    alert_type: "aggregate_report"
    query: "aggregate_report.query_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "NEW_GOVERNANCE_PROPOSAL"
    alert_type: "submit_proposal"
    query: "submit_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "GOVERNANCE_PROPOSAL_FINISHED_INACTIVE"
    alert_type: "inactive_proposal"
    query: "inactive_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "GOVERNANCE_PROPOSAL_FINISHED_ACTIVE"
    alert_type: "active_proposal"
    query: "active_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "NEW_VALIDATOR_CREATED"
    alert_type: "create_validator"
    query: "create_validator.validator EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "JAILED_EVENT"
    alert_type: "slash"
    query: "slash.jailed EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "NEW_BRIDGE_VALIDATOR_SET"
    alert_type: "new_bridge_validator_set"
    query: "new_bridge_validator_set.timestamp EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "SLASH_EVENT"
    alert_type: "slash"
    query: "slash.address EXISTS"
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "BLOCK-TIME-ALERT"
    alert_type: "block-time-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "LIVENESS-ALERT"
    alert_type: "liveness-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "CRASH-ALERT"
    alert_type: "crash-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
  - alert_name: "VALSET_UPDATE_ANALYSIS"
    alert_type: "valset_update_analysis"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL" 