version: "2"

run:
  tests: true
  timeout: 15m
  allow-parallel-runners: true

output:
  formats:
    text:
      print-linter-name: true
  show-stats: true

linters:
  disable:
    - depguard
  enable:
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unused

  settings:
    revive:
      rules:
        - name: redefines-builtin-id
          disabled: true
    gosec:
      includes:
        - G102
        - G103
        - G104
        - G106
        - G107
        - G108
        - G109
        - G110
        - G111
        - G112
        - G113
        - G114
        - G201
        - G202
        - G203
        - G204
        - G307
        - G401
        - G402
        - G403
        - G404
        - G501
        - G502
        - G503
        - G504
        - G505
        - G601
    misspell:
      locale: US
    dogsled:
      max-blank-identifiers: 8
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: false
    gocritic:
      disabled-checks:
        - regexpMust
        - appendAssign
        - ifElseChain
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.ResponseWriter).Write
        - (*database/sql.Rows).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.RemoveAll
        - os.Remove
        # Cosmos SDK iterator patterns - Close() errors are typically ignored in defer
        - (cosmossdk.io/store/types.Iterator).Close
        - (github.com/cosmos/cosmos-sdk/types.Iterator).Close
        - (*github.com/cometbft/cometbft/libs/pubsub.Server).Stop
        - (cosmossdk.io/collections.KeySetIterator).Close
        - (cosmossdk.io/collections.Iterator).Close

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - server/grpc/gogoreflection/fix_registration.go
      - fix_registration.go
      - ".*\\.pb\\.go$"
      - ".*\\.pb\\.gw\\.go$"
      - ".*\\.pulsar\\.go$"
      - crypto/keys/secp256k1/internal/*
    rules:
      # Weak random number generator - acceptable for non-crypto uses
      - text: "Use of weak random number generator"
        linters:
          - gosec
      # Style check exclusions
      - text: "ST1003:"
        linters:
          - stylecheck
      - text: "ST1016:"
        linters:
          - stylecheck
      # Deprecated API exclusions for migrations
      - path: "migrations"
        text: "SA1019:"
        linters:
          - staticcheck
      - text: "SA1019: codec.NewAminoCodec is deprecated"
        linters:
          - staticcheck
      - text: "SA1019: legacybech32.MustMarshalPubKey"
        linters:
          - staticcheck
      - text: "SA1019: legacybech32.MarshalPubKey"
        linters:
          - staticcheck
      - text: "SA1019: legacybech32.UnmarshalPubKey"
        linters:
          - staticcheck
      - text: "SA1019: params.SendEnabled is deprecated"
        linters:
          - staticcheck
      - text: "leading space"
        linters:
          - nolintlint
      # Exclude optional refactoring suggestions (QF = quick fix)
      - text: "QF1003:"
        linters:
          - staticcheck
      - text: "QF1007:"
        linters:
          - staticcheck
      - text: "QF1008:"
        linters:
          - staticcheck
      - text: "QF1010:"
        linters:
          - staticcheck
      - text: "QF1012:"
        linters:
          - staticcheck
      # Exclude gosec/errcheck/nolintlint for scripts (test scripts)
      - path: "scripts/"
        linters:
          - gosec
          - errcheck
          - nolintlint
      # Exclude G104 (unhandled errors) and QF suggestions for utility scripts
      - path: "utils/"
        linters:
          - gosec
      - path: "testutil/"
        linters:
          - gosec
      # e2e tests - relaxed linting
      - path: "e2e/"
        linters:
          - gosec
          - errcheck
      - text: "G301:"
        linters:
          - gosec
      - text: "G302:"
        linters:
          - gosec
      - text: "G304:"
        linters:
          - gosec
      - text: "G103:"
        linters:
          - gosec
      # G115: integer overflow conversion - common in Cosmos SDK
      - text: "G115:"
        linters:
          - gosec
      # Exclude iterator Close() errors - standard pattern in Cosmos SDK
      - source: "defer.*\\.Close\\(\\)"
        linters:
          - errcheck

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gofumpt:
      extra-rules: true
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
