{
 "title": "Layer Validators Tracker test set up",
 "description": "Dashboard to monitor the teams layer validators",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain_id",
    "query": {
     "query": "label_values(cosmos_validators_status, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "moniker",
    "query": {
     "query": "label_values(cosmos_validator_status, moniker)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_memory_MemTotal_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Oracle/Daemon Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average gas consumed (loya) SubmitValue",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(submit_value_gas_consumed{chain_id=\"$chain_id\"}[1h]) * 0.000025",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of reports in aggregates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(reports_in_aggregate_report_submitted{chain_id=\"$chain_id\"}[10m])) by (query_id) / sum(rate(reports_in_aggregate_aggregate_created{chain_id=\"$chain_id\"}[10m])) by (query_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reporter Power in Aggregates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "reporter_power_in_aggregates{chain_id=\"$chain_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of successful tx attempts",
   "type": "timeseries",
   "description": "percentage of the total successful daemon tx vs total attempted transactions",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "100 * (rate(daemon_sending_txs_success{chain_id=\"$chain_id\"}[1h]) / rate(daemon_sending_txs_called{chain_id=\"$chain_id\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "End Blockers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Avg Dispute End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(end_blocker_sum{chain_id=\"$chain_id\", module=\"dispute\"}[10m]) / rate(end_blocker_count{chain_id=\"$chain_id\", module=\"dispute\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Bridge End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "increase(end_blocker_sum{chain_id=\"$chain_id\", module=\"bridge\"}[30s]) / increase(end_blocker_count{chain_id=\"$chain_id\", module=\"bridge\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Reporter End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(end_blocker_sum{chain_id=\"$chain_id\", module=\"reporter\"}[1h]) / rate(end_blocker_count{chain_id=\"$chain_id\", module=\"reporter\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Oracle End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "increase(end_blocker_sum{chain_id=\"$chain_id\", module=\"oracle\"}[30s]) / increase(end_blocker_count{chain_id=\"$chain_id\", module=\"oracle\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Begin Blockers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Avg Mint Begin Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(begin_blocker_sum{chain_id=\"$chain_id\", module=\"mint\"}[10m]) / rate(begin_blocker_count{chain_id=\"$chain_id\", module=\"mint\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Distribution Begin Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 15 },
   "targets": [
    {
     "expr": "rate(begin_blocker_sum{chain_id=\"$chain_id\", module=\"distribution\"}[10m]) / rate(begin_blocker_count{chain_id=\"$chain_id\", module=\"distribution\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Dispute Begin Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "rate(begin_blocker_sum{chain_id=\"$chain_id\", module=\"dispute\"}[10m]) / rate(begin_blocker_count{chain_id=\"$chain_id\", module=\"dispute\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Chain health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators-cometbft_consensus_missing_validators{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"} / cometbft_consensus_validators_power{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"})"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cometbft_consensus_validator_missed_blocks{chain_id=\"$chain_id\"} > 0))"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{chain_id=\"$chain_id\", job=~\"${JOB_NAMES}\"}"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{chain_id=\"$chain_id\", job=~\"${JOB_NAMES\"}"
    }
   ]
  },
  {
   "title": "Top missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cometbft_consensus_validator_missed_blocks{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cometbft_consensus_height{chain_id=\"$chain_id\"}[1m])"
    }
   ]
  },
  {
   "title": "Change in Total Bonded Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "delta(cometbft_consensus_validators_power{chain_id=\"$chain_id\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Our Validators Power Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum by(validator_address) (cometbft_consensus_validator_power{chain_id=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block times",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(cometbft_consensus_block_interval_seconds_bucket{chain_id=\"$chain_id\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}