event_types:
  - alert_name: "NEW_DISPUTE"
    alert_type: "new_dispute"
    query: "new_dispute.reporter EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626376671100928/YrIWOL6p-PGtuO6Gd1VtcwdINj3Kl5oLP9AbjZvimw6KuHExmD_SrsKfNWBS1IvCqGtE"
  - alert_name: "DISPUTE_ROUND_ADDED"
    alert_type: "added_dispute_round"
    query: "added_dispute_round.dispute_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626376671100928/YrIWOL6p-PGtuO6Gd1VtcwdINj3Kl5oLP9AbjZvimw6KuHExmD_SrsKfNWBS1IvCqGtE"
  - alert_name: "DISPUTE_EXECUTED"
    alert_type: "dispute_executed"
    query: "dispute_executed.dispute_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626376671100928/YrIWOL6p-PGtuO6Gd1VtcwdINj3Kl5oLP9AbjZvimw6KuHExmD_SrsKfNWBS1IvCqGtE"
  - alert_name: "DEPOSIT_CLAIMED"
    alert_type: "deposit_claimed"
    query: "deposit_claimed.deposit_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626604061098004/N2J-8SMh0KTQb0xRlRAy70fUDRG6Q2K4zV1uN6S6TR9wCnhhMW9wYGhc-lqfKhZwhunm"
  - alert_name: "WITHDRAWAL_INITIATED"
    alert_type: "tokens_withdrawn"
    query: "tokens_withdrawn.withdraw_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626604061098004/N2J-8SMh0KTQb0xRlRAy70fUDRG6Q2K4zV1uN6S6TR9wCnhhMW9wYGhc-lqfKhZwhunm"
  - alert_name: "TIP_ADDED"
    alert_type: "tip_added"
    query: "tip_added.query_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626762651795486/1hPTUdJXN-wfywA59bLXA2eK0Y1RszDufPaCX-mN2qOJr4JP1DrIZnIdQyZji6Ixd2l2"
  - alert_name: "AGGREGATE_REPORT"
    alert_type: "aggregate_report"
    query: "aggregate_report.query_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626762651795486/1hPTUdJXN-wfywA59bLXA2eK0Y1RszDufPaCX-mN2qOJr4JP1DrIZnIdQyZji6Ixd2l2"
  - alert_name: "NEW_GOVERNANCE_PROPOSAL"
    alert_type: "submit_proposal"
    query: "submit_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626880440565841/txqbHs1ivemapzU8Nu8AezX52KpwSpp-4HDTBOziIkpDMOy_kYtwatV0RMsInKrCu0D9"
  - alert_name: "GOVERNANCE_PROPOSAL_FINISHED_INACTIVE"
    alert_type: "inactive_proposal"
    query: "inactive_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626880440565841/txqbHs1ivemapzU8Nu8AezX52KpwSpp-4HDTBOziIkpDMOy_kYtwatV0RMsInKrCu0D9"
  - alert_name: "GOVERNANCE_PROPOSAL_FINISHED_ACTIVE"
    alert_type: "active_proposal"
    query: "active_proposal.proposal_id EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380626880440565841/txqbHs1ivemapzU8Nu8AezX52KpwSpp-4HDTBOziIkpDMOy_kYtwatV0RMsInKrCu0D9"
  - alert_name: "NEW_VALIDATOR_CREATED"
    alert_type: "create_validator"
    query: "create_validator.validator EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380627018399350815/3Jqt_nIbOiD1dh3jwpRQa_AvpKZW9lGxgmYJwF5SfBsLRwBpZX_vyhFkO8-wQQ5vlzWG"
  - alert_name: "JAILED_EVENT"
    alert_type: "slash"
    query: "slash.jailed EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380627018399350815/3Jqt_nIbOiD1dh3jwpRQa_AvpKZW9lGxgmYJwF5SfBsLRwBpZX_vyhFkO8-wQQ5vlzWG"
  - alert_name: "NEW_BRIDGE_VALIDATOR_SET"
    alert_type: "new_bridge_validator_set"
    query: "new_bridge_validator_set.timestamp EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380627115267067935/pV4EA4SGubs0Bf-bVKIFy5crzs2C2QW20biI8P2GhNAirevaXB5j6W5v1rzA785HGnRq"
  - alert_name: "SLASH_EVENT"
    alert_type: "slash"
    query: "slash.address EXISTS"
    webhook_url: "https://discord.com/api/webhooks/1380627018399350815/3Jqt_nIbOiD1dh3jwpRQa_AvpKZW9lGxgmYJwF5SfBsLRwBpZX_vyhFkO8-wQQ5vlzWG"
  - alert_name: "BLOCK-TIME-ALERT"
    alert_type: "block-time-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/1381667733711753346/5Rf2AFFHA4Fi40Om_WVNagNK5fJhlyV1bUnwLZ1zgFrCyTVw7baDZ_I2BjAGI25It3a_"
  - alert_name: "LIVENESS-ALERT"
    alert_type: "liveness-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/1275539999235768390/doH7Q0Ayvp4k5ax2M-vmkH6hc0E6_eM8vws49yzg07fGiJCvkwIU-mjJf410G5kt5sLX"
  - alert_name: "CRASH-ALERT"
    alert_type: "crash-alert"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/1380633111230152756/jVPUyQEDpysX4IkzmproRFGByVyP0C45zfeBUvgeYMBYa_JBIctZN89QIznxDdr99kkb"
  - alert_name: "VALSET_UPDATE_ANALYSIS"
    alert_type: "valset_update_analysis"
    query: ""
    webhook_url: "https://discord.com/api/webhooks/1380627115267067935/pV4EA4SGubs0Bf-bVKIFy5crzs2C2QW20biI8P2GhNAirevaXB5j6W5v1rzA785HGnRq"
