syntax = "proto3";
package layer.reporter;

import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "layer/reporter/params.proto";
import "layer/reporter/selection.proto";
import "layer/reporter/tip_unlock.proto";
import "layer/reporter/token_origin.proto";

option go_package = "github.com/tellor-io/layer/x/reporter/types";

// GenesisState defines the reporter module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  repeated SelectorTipsStateEntry selectorTips = 2;
  repeated DisputedDelegationAmountStateEntry disputed_delegation_amounts = 3;
  repeated FeePaidFromStakeStateEntry fee_paid_from_stake = 4;
  repeated TipUnlockStateEntry tip_unlocks = 5;
  // tip_unlock_id is the next unlock id to allocate (TipUnlockID sequence peek value).
  uint64 tip_unlock_id = 6;
}

message TipUnlockStateEntry {
  bytes selector_address = 1;
  uint64 unlock_id = 2;
  TipUnlockEntry entry = 3 [(gogoproto.nullable) = false];
}

message SelectorTipsStateEntry {
  bytes selector_address = 1;
  string tips = 2 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

message DisputedDelegationAmountStateEntry {
  bytes hash_id = 1;
  DelegationsAmounts delegation_amount = 2;
}

message FeePaidFromStakeStateEntry {
  bytes hash_id = 1;
  DelegationsAmounts delegation_amount = 2;
}


