global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'validator-0'
    scrape_interval: 5s
    metrics_path: '/'
    static_configs:
      - targets: ['validator-node-0:26660']
    params:
      format: ['prometheus']
  - job_name: 'validator-1'
    scrape_interval: 5s
    metrics_path: '/'
    static_configs:
      - targets: ['validator-node-1:26660']
    params:
      format: ['prometheus']
  - job_name: 'validator-2'
    scrape_interval: 5s
    metrics_path: '/'
    static_configs:
      - targets: ['validator-node-2:26660']
    params:
      format: ['prometheus']
  - job_name: 'reporter-0'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['validator-node-0:26661']
    params:
      format: ['prometheus']
  - job_name: 'reporter-1'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['validator-node-1:26661']
    params:
      format: ['prometheus']
  - job_name: 'reporter-2'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['validator-node-2:26661']
    params:
      format: ['prometheus']