// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layer/reporter/oracle_reporter.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	types "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OracleReporter is the struct that holds the data for a reporter
type OracleReporter struct {
	// tokens is the amount of tokens the reporter has
	TotalTokens cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_tokens,json=totalTokens,proto3,customtype=cosmossdk.io/math.Int" json:"total_tokens"`
	// commission for the reporter
	Commission *types.Commission `protobuf:"bytes,2,opt,name=commission,proto3" json:"commission,omitempty"`
	// jailed is a bool whether the reporter is jailed or not
	Jailed bool `protobuf:"varint,3,opt,name=jailed,proto3" json:"jailed,omitempty"`
	// jailed_until is the time the reporter is jailed until
	JailedUntil time.Time `protobuf:"bytes,4,opt,name=jailed_until,json=jailedUntil,proto3,stdtime" json:"jailed_until"`
}

func (m *OracleReporter) Reset()         { *m = OracleReporter{} }
func (m *OracleReporter) String() string { return proto.CompactTextString(m) }
func (*OracleReporter) ProtoMessage()    {}
func (*OracleReporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_28310cb3dcf79802, []int{0}
}
func (m *OracleReporter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OracleReporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OracleReporter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OracleReporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OracleReporter.Merge(m, src)
}
func (m *OracleReporter) XXX_Size() int {
	return m.Size()
}
func (m *OracleReporter) XXX_DiscardUnknown() {
	xxx_messageInfo_OracleReporter.DiscardUnknown(m)
}

var xxx_messageInfo_OracleReporter proto.InternalMessageInfo

func (m *OracleReporter) GetCommission() *types.Commission {
	if m != nil {
		return m.Commission
	}
	return nil
}

func (m *OracleReporter) GetJailed() bool {
	if m != nil {
		return m.Jailed
	}
	return false
}

func (m *OracleReporter) GetJailedUntil() time.Time {
	if m != nil {
		return m.JailedUntil
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*OracleReporter)(nil), "layer.reporter.OracleReporter")
}

func init() {
	proto.RegisterFile("layer/reporter/oracle_reporter.proto", fileDescriptor_28310cb3dcf79802)
}

var fileDescriptor_28310cb3dcf79802 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xe3, 0x05, 0xad, 0xc0, 0x5d, 0x56, 0x22, 0x02, 0x14, 0x7a, 0x48, 0xaa, 0xd5, 0x1e,
	0x2a, 0x56, 0x6b, 0x6b, 0xe1, 0x0d, 0x82, 0x38, 0xac, 0x84, 0x40, 0x8a, 0x96, 0x0b, 0x97, 0xc8,
	0xc9, 0x9a, 0xac, 0xa9, 0x9d, 0x89, 0xe2, 0x29, 0xa2, 0xaf, 0xc0, 0xa9, 0x8f, 0xc1, 0x91, 0x03,
	0x0f, 0xd1, 0x63, 0xc5, 0x09, 0x71, 0x28, 0xa8, 0x3d, 0xf0, 0x1a, 0xa8, 0xb6, 0x03, 0x5c, 0x22,
	0xff, 0x93, 0xef, 0x9f, 0x99, 0x5f, 0x43, 0x4f, 0xb5, 0x58, 0xc8, 0x9e, 0xf7, 0xb2, 0x83, 0x1e,
	0x65, 0xcf, 0xa1, 0x17, 0xb5, 0x96, 0xe5, 0xa0, 0x59, 0xd7, 0x03, 0x42, 0x7c, 0xec, 0x28, 0x36,
	0x54, 0xc7, 0xf7, 0x85, 0x51, 0x2d, 0x70, 0xf7, 0xf5, 0xc8, 0xf8, 0xb4, 0x06, 0x6b, 0xc0, 0x72,
	0x8b, 0x62, 0xa6, 0xda, 0x86, 0x7f, 0xb8, 0xa8, 0x24, 0x8a, 0x8b, 0x41, 0x07, 0xea, 0xb1, 0xa7,
	0x4a, 0xa7, 0xb8, 0x17, 0xe1, 0xd7, 0x83, 0x06, 0x1a, 0xf0, 0xf5, 0xfd, 0x2b, 0x54, 0xb3, 0x06,
	0xa0, 0xd1, 0x92, 0x3b, 0x55, 0xcd, 0xdf, 0x71, 0x54, 0x46, 0x5a, 0x14, 0xa6, 0xf3, 0xc0, 0xc9,
	0xa7, 0x03, 0x7a, 0xfc, 0xda, 0x2d, 0x5d, 0x84, 0xed, 0xe2, 0x57, 0xf4, 0x08, 0x01, 0x85, 0x2e,
	0x11, 0x66, 0xb2, 0xb5, 0x09, 0x99, 0x90, 0xe9, 0xdd, 0xfc, 0x6c, 0xb5, 0xc9, 0xa2, 0x1f, 0x9b,
	0xec, 0xa1, 0x9f, 0x6a, 0xaf, 0x67, 0x4c, 0x01, 0x37, 0x02, 0x6f, 0xd8, 0x65, 0x8b, 0xdf, 0xbe,
	0x9e, 0xd3, 0xb0, 0xce, 0x65, 0x8b, 0xc5, 0xc8, 0x35, 0xb8, 0x72, 0xfe, 0x38, 0xa7, 0xb4, 0x06,
	0x63, 0x94, 0xb5, 0x0a, 0xda, 0xe4, 0x60, 0x42, 0xa6, 0xa3, 0xa7, 0x27, 0x2c, 0xd0, 0x43, 0xbe,
	0x90, 0x97, 0x3d, 0xff, 0x4b, 0x16, 0xff, 0xb9, 0xe2, 0x47, 0xf4, 0xf0, 0xbd, 0x50, 0x5a, 0x5e,
	0x27, 0xb7, 0x26, 0x64, 0x7a, 0xa7, 0x08, 0x2a, 0x7e, 0x49, 0x8f, 0xfc, 0xab, 0x9c, 0xb7, 0xa8,
	0x74, 0x72, 0xdb, 0x75, 0x1f, 0x33, 0x1f, 0x9b, 0x0d, 0xb1, 0xd9, 0xd5, 0x10, 0x3b, 0xbf, 0xb7,
	0xcf, 0xb1, 0xfc, 0x99, 0x91, 0xcf, 0xbf, 0xbf, 0x3c, 0x21, 0xc5, 0xc8, 0xdb, 0xdf, 0xec, 0xdd,
	0xf9, 0x8b, 0xd5, 0x36, 0x25, 0xeb, 0x6d, 0x4a, 0x7e, 0x6d, 0x53, 0xb2, 0xdc, 0xa5, 0xd1, 0x7a,
	0x97, 0x46, 0xdf, 0x77, 0x69, 0xf4, 0xf6, 0xac, 0x51, 0x78, 0x33, 0xaf, 0x58, 0x0d, 0x86, 0xa3,
	0xd4, 0x1a, 0xfa, 0x73, 0x05, 0xdc, 0x1f, 0xff, 0xe3, 0xbf, 0xf3, 0xe3, 0xa2, 0x93, 0xb6, 0x3a,
	0x74, 0x63, 0x9f, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x21, 0x3e, 0xbc, 0x3f, 0x1d, 0x02, 0x00,
	0x00,
}

func (m *OracleReporter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OracleReporter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OracleReporter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.JailedUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.JailedUntil):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintOracleReporter(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x22
	if m.Jailed {
		i--
		if m.Jailed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Commission != nil {
		{
			size, err := m.Commission.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOracleReporter(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.TotalTokens.Size()
		i -= size
		if _, err := m.TotalTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintOracleReporter(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintOracleReporter(dAtA []byte, offset int, v uint64) int {
	offset -= sovOracleReporter(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OracleReporter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalTokens.Size()
	n += 1 + l + sovOracleReporter(uint64(l))
	if m.Commission != nil {
		l = m.Commission.Size()
		n += 1 + l + sovOracleReporter(uint64(l))
	}
	if m.Jailed {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.JailedUntil)
	n += 1 + l + sovOracleReporter(uint64(l))
	return n
}

func sovOracleReporter(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOracleReporter(x uint64) (n int) {
	return sovOracleReporter(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OracleReporter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOracleReporter
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OracleReporter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OracleReporter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOracleReporter
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOracleReporter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commission", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracleReporter
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracleReporter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Commission == nil {
				m.Commission = &types.Commission{}
			}
			if err := m.Commission.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Jailed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Jailed = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOracleReporter
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOracleReporter
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.JailedUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOracleReporter(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOracleReporter
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOracleReporter(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOracleReporter
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOracleReporter
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOracleReporter
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOracleReporter
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOracleReporter
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOracleReporter        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOracleReporter          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOracleReporter = fmt.Errorf("proto: unexpected end of group")
)
