// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layer/reporter/selection.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Selection is a type that represents a  delegator's selection
type Selection struct {
	// reporter is the address of the reporter being delegated to
	Reporter []byte `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	// locked_until_time is the time until which the tokens are locked before they
	// can be used for reporting again
	LockedUntilTime time.Time `protobuf:"bytes,2,opt,name=locked_until_time,json=lockedUntilTime,proto3,stdtime" json:"locked_until_time"`
	// delegations_count is the number of delegations to the reporter
	DelegationsCount uint64 `protobuf:"varint,3,opt,name=delegations_count,json=delegationsCount,proto3" json:"delegations_count,omitempty"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b0e998201c9cd64, []int{0}
}
func (m *Selection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(m, src)
}
func (m *Selection) XXX_Size() int {
	return m.Size()
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

func (m *Selection) GetReporter() []byte {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *Selection) GetLockedUntilTime() time.Time {
	if m != nil {
		return m.LockedUntilTime
	}
	return time.Time{}
}

func (m *Selection) GetDelegationsCount() uint64 {
	if m != nil {
		return m.DelegationsCount
	}
	return 0
}

// FormattedSelection is a type that represents a  delegator's selection for the SelectionsTo query
type FormattedSelection struct {
	// reporter is the address of the reporter being delegated to
	Reporter string `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	Selector string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	// locked_until_time is the time until which the tokens are locked before they
	// can be used for reporting again
	LockedUntilTime time.Time `protobuf:"bytes,3,opt,name=locked_until_time,json=lockedUntilTime,proto3,stdtime" json:"locked_until_time"`
	// delegations_count is the number of delegations the selector has made to validators
	DelegationsCount uint64 `protobuf:"varint,4,opt,name=delegations_count,json=delegationsCount,proto3" json:"delegations_count,omitempty"`
	// delegations_total is the total power of the delegations the selector has made to validators
	DelegationsTotal uint64 `protobuf:"varint,5,opt,name=delegations_total,json=delegationsTotal,proto3" json:"delegations_total,omitempty"`
}

func (m *FormattedSelection) Reset()         { *m = FormattedSelection{} }
func (m *FormattedSelection) String() string { return proto.CompactTextString(m) }
func (*FormattedSelection) ProtoMessage()    {}
func (*FormattedSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b0e998201c9cd64, []int{1}
}
func (m *FormattedSelection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FormattedSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FormattedSelection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FormattedSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormattedSelection.Merge(m, src)
}
func (m *FormattedSelection) XXX_Size() int {
	return m.Size()
}
func (m *FormattedSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_FormattedSelection.DiscardUnknown(m)
}

var xxx_messageInfo_FormattedSelection proto.InternalMessageInfo

func (m *FormattedSelection) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

func (m *FormattedSelection) GetSelector() string {
	if m != nil {
		return m.Selector
	}
	return ""
}

func (m *FormattedSelection) GetLockedUntilTime() time.Time {
	if m != nil {
		return m.LockedUntilTime
	}
	return time.Time{}
}

func (m *FormattedSelection) GetDelegationsCount() uint64 {
	if m != nil {
		return m.DelegationsCount
	}
	return 0
}

func (m *FormattedSelection) GetDelegationsTotal() uint64 {
	if m != nil {
		return m.DelegationsTotal
	}
	return 0
}

func init() {
	proto.RegisterType((*Selection)(nil), "layer.reporter.Selection")
	proto.RegisterType((*FormattedSelection)(nil), "layer.reporter.FormattedSelection")
}

func init() { proto.RegisterFile("layer/reporter/selection.proto", fileDescriptor_0b0e998201c9cd64) }

var fileDescriptor_0b0e998201c9cd64 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xbf, 0x4e, 0xc2, 0x40,
	0x1c, 0xee, 0x09, 0x1a, 0xa8, 0x46, 0xa5, 0x71, 0xa8, 0x1d, 0x0e, 0xc2, 0x44, 0x42, 0xec, 0x25,
	0xfa, 0x06, 0x18, 0x9d, 0x4d, 0xc5, 0xc5, 0xa5, 0x29, 0xe5, 0xac, 0x8d, 0xd7, 0xfe, 0x9a, 0xeb,
	0xaf, 0x89, 0xbc, 0x05, 0x4f, 0xe1, 0xb3, 0x30, 0x32, 0x3a, 0xa9, 0x81, 0x97, 0x70, 0x34, 0xd7,
	0xa3, 0x48, 0x14, 0x37, 0x97, 0xa6, 0xdf, 0x9f, 0xeb, 0xf7, 0x7d, 0xcd, 0x99, 0x54, 0x04, 0x13,
	0x2e, 0x99, 0xe4, 0x19, 0x48, 0xe4, 0x92, 0xe5, 0x5c, 0xf0, 0x10, 0x63, 0x48, 0xdd, 0x4c, 0x02,
	0x82, 0x75, 0x58, 0xea, 0x6e, 0xa5, 0x3b, 0xad, 0x20, 0x89, 0x53, 0x60, 0xe5, 0x53, 0x5b, 0x9c,
	0xd3, 0x10, 0xf2, 0x04, 0x72, 0xbf, 0x44, 0x4c, 0x83, 0x95, 0x74, 0x12, 0x41, 0x04, 0x9a, 0x57,
	0x6f, 0x2b, 0xb6, 0x1d, 0x01, 0x44, 0x82, 0xb3, 0x12, 0x8d, 0x8a, 0x07, 0x86, 0x71, 0xc2, 0x73,
	0x0c, 0x92, 0x4c, 0x1b, 0xba, 0x2f, 0xc4, 0x6c, 0xde, 0x56, 0x45, 0x2c, 0xc7, 0x6c, 0x54, 0xf1,
	0x36, 0xe9, 0x90, 0xde, 0x81, 0xb7, 0xc6, 0xd6, 0x8d, 0xd9, 0x12, 0x10, 0x3e, 0xf1, 0xb1, 0x5f,
	0xa4, 0x18, 0x0b, 0x5f, 0x7d, 0xc9, 0xde, 0xe9, 0x90, 0xde, 0xfe, 0xb9, 0xe3, 0xea, 0x18, 0xb7,
	0x8a, 0x71, 0x87, 0x55, 0xcc, 0xa0, 0x31, 0x7b, 0x6b, 0x1b, 0xd3, 0xf7, 0x36, 0xf1, 0x8e, 0xf4,
	0xf1, 0x3b, 0x75, 0x5a, 0xe9, 0x56, 0xdf, 0x6c, 0x8d, 0xb9, 0xe0, 0x51, 0xa0, 0xb2, 0x73, 0x3f,
	0x84, 0x22, 0x45, 0xbb, 0xd6, 0x21, 0xbd, 0xba, 0x77, 0xbc, 0x21, 0x5c, 0x2a, 0xbe, 0xfb, 0x49,
	0x4c, 0xeb, 0x1a, 0x64, 0x12, 0x20, 0xf2, 0xf1, 0xdf, 0x8d, 0x9b, 0x1b, 0x8d, 0x1d, 0xb3, 0xa1,
	0xff, 0x31, 0xc8, 0xb2, 0x68, 0xd3, 0x5b, 0xe3, 0xed, 0x6b, 0x6a, 0xff, 0xbe, 0xa6, 0xbe, 0x7d,
	0xcd, 0x4f, 0x33, 0x02, 0x06, 0xc2, 0xde, 0xfd, 0x65, 0x1e, 0x2a, 0x7e, 0x70, 0x35, 0x5b, 0x50,
	0x32, 0x5f, 0x50, 0xf2, 0xb1, 0xa0, 0x64, 0xba, 0xa4, 0xc6, 0x7c, 0x49, 0x8d, 0xd7, 0x25, 0x35,
	0xee, 0xfb, 0x51, 0x8c, 0x8f, 0xc5, 0xc8, 0x0d, 0x21, 0x61, 0xc8, 0x85, 0x00, 0x79, 0x16, 0x03,
	0xd3, 0xf7, 0xec, 0xf9, 0xfb, 0xa6, 0xe1, 0x24, 0xe3, 0xf9, 0x68, 0xaf, 0xdc, 0x73, 0xf1, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x75, 0x23, 0xfd, 0x3f, 0x88, 0x02, 0x00, 0x00,
}

func (m *Selection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Selection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Selection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DelegationsCount != 0 {
		i = encodeVarintSelection(dAtA, i, uint64(m.DelegationsCount))
		i--
		dAtA[i] = 0x18
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LockedUntilTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LockedUntilTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSelection(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.Reporter) > 0 {
		i -= len(m.Reporter)
		copy(dAtA[i:], m.Reporter)
		i = encodeVarintSelection(dAtA, i, uint64(len(m.Reporter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FormattedSelection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FormattedSelection) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FormattedSelection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DelegationsTotal != 0 {
		i = encodeVarintSelection(dAtA, i, uint64(m.DelegationsTotal))
		i--
		dAtA[i] = 0x28
	}
	if m.DelegationsCount != 0 {
		i = encodeVarintSelection(dAtA, i, uint64(m.DelegationsCount))
		i--
		dAtA[i] = 0x20
	}
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LockedUntilTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LockedUntilTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintSelection(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if len(m.Selector) > 0 {
		i -= len(m.Selector)
		copy(dAtA[i:], m.Selector)
		i = encodeVarintSelection(dAtA, i, uint64(len(m.Selector)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Reporter) > 0 {
		i -= len(m.Reporter)
		copy(dAtA[i:], m.Reporter)
		i = encodeVarintSelection(dAtA, i, uint64(len(m.Reporter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSelection(dAtA []byte, offset int, v uint64) int {
	offset -= sovSelection(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Selection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reporter)
	if l > 0 {
		n += 1 + l + sovSelection(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LockedUntilTime)
	n += 1 + l + sovSelection(uint64(l))
	if m.DelegationsCount != 0 {
		n += 1 + sovSelection(uint64(m.DelegationsCount))
	}
	return n
}

func (m *FormattedSelection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reporter)
	if l > 0 {
		n += 1 + l + sovSelection(uint64(l))
	}
	l = len(m.Selector)
	if l > 0 {
		n += 1 + l + sovSelection(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LockedUntilTime)
	n += 1 + l + sovSelection(uint64(l))
	if m.DelegationsCount != 0 {
		n += 1 + sovSelection(uint64(m.DelegationsCount))
	}
	if m.DelegationsTotal != 0 {
		n += 1 + sovSelection(uint64(m.DelegationsTotal))
	}
	return n
}

func sovSelection(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSelection(x uint64) (n int) {
	return sovSelection(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Selection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelection
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Selection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Selection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reporter", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSelection
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSelection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reporter = append(m.Reporter[:0], dAtA[iNdEx:postIndex]...)
			if m.Reporter == nil {
				m.Reporter = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedUntilTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelection
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSelection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LockedUntilTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationsCount", wireType)
			}
			m.DelegationsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelegationsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelection(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSelection
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FormattedSelection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSelection
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FormattedSelection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FormattedSelection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reporter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelection
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSelection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reporter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Selector", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSelection
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSelection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Selector = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedUntilTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSelection
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSelection
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LockedUntilTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationsCount", wireType)
			}
			m.DelegationsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelegationsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationsTotal", wireType)
			}
			m.DelegationsTotal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DelegationsTotal |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSelection(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSelection
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSelection(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSelection
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSelection
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSelection
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSelection
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSelection
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSelection        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSelection          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSelection = fmt.Errorf("proto: unexpected end of group")
)
