// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	math "cosmossdk.io/math"

	mock "github.com/stretchr/testify/mock"

	reportertypes "github.com/tellor-io/layer/x/reporter/types"

	types "github.com/cosmos/cosmos-sdk/types"
)

// ReporterKeeper is an autogenerated mock type for the ReporterKeeper type
type ReporterKeeper struct {
	mock.Mock
}

// AddAmountToStake provides a mock function with given fields: ctx, acc, amt
func (_m *ReporterKeeper) AddAmountToStake(ctx context.Context, acc types.AccAddress, amt math.Int) (math.Int, math.Int, error) {
	ret := _m.Called(ctx, acc, amt)

	var r0 math.Int
	var r1 math.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, math.Int) (math.Int, math.Int, error)); ok {
		return rf(ctx, acc, amt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, math.Int) math.Int); ok {
		r0 = rf(ctx, acc, amt)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress, math.Int) math.Int); ok {
		r1 = rf(ctx, acc, amt)
	} else {
		r1 = ret.Get(1).(math.Int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.AccAddress, math.Int) error); ok {
		r2 = rf(ctx, acc, amt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delegation provides a mock function with given fields: ctx, delegator
func (_m *ReporterKeeper) Delegation(ctx context.Context, delegator types.AccAddress) (reportertypes.Selection, error) {
	ret := _m.Called(ctx, delegator)

	var r0 reportertypes.Selection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) (reportertypes.Selection, error)); ok {
		return rf(ctx, delegator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) reportertypes.Selection); ok {
		r0 = rf(ctx, delegator)
	} else {
		r0 = ret.Get(0).(reportertypes.Selection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress) error); ok {
		r1 = rf(ctx, delegator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EscrowReporterStake provides a mock function with given fields: ctx, reporterAddr, power, height, amt, queryId, hashId
func (_m *ReporterKeeper) EscrowReporterStake(ctx context.Context, reporterAddr types.AccAddress, power uint64, height uint64, amt math.Int, queryId []byte, hashId []byte) error {
	ret := _m.Called(ctx, reporterAddr, power, height, amt, queryId, hashId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, uint64, uint64, math.Int, []byte, []byte) error); ok {
		r0 = rf(ctx, reporterAddr, power, height, amt, queryId, hashId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DisputedDelegationTotal provides a mock function with given fields: ctx, hashId
func (_m *ReporterKeeper) DisputedDelegationTotal(ctx context.Context, hashId []byte) (math.Int, error) {
	ret := _m.Called(ctx, hashId)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (math.Int, error)); ok {
		return rf(ctx, hashId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) math.Int); ok {
		r0 = rf(ctx, hashId)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, hashId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeeRefund provides a mock function with given fields: ctx, hashId, payer, amt
func (_m *ReporterKeeper) FeeRefund(ctx context.Context, hashId []byte, payer types.AccAddress, amt math.Int) (math.Int, math.Int, error) {
	ret := _m.Called(ctx, hashId, payer, amt)

	var r0 math.Int
	var r1 math.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, types.AccAddress, math.Int) (math.Int, math.Int, error)); ok {
		return rf(ctx, hashId, payer, amt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, types.AccAddress, math.Int) math.Int); ok {
		r0 = rf(ctx, hashId, payer, amt)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, types.AccAddress, math.Int) math.Int); ok {
		r1 = rf(ctx, hashId, payer, amt)
	} else {
		r1 = ret.Get(1).(math.Int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []byte, types.AccAddress, math.Int) error); ok {
		r2 = rf(ctx, hashId, payer, amt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FeePaidFromStakeTotalByPayer provides a mock function with given fields: ctx, hashId, payer
func (_m *ReporterKeeper) FeePaidFromStakeTotalByPayer(ctx context.Context, hashId []byte, payer types.AccAddress) (math.Int, error) {
	ret := _m.Called(ctx, hashId, payer)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, types.AccAddress) (math.Int, error)); ok {
		return rf(ctx, hashId, payer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, types.AccAddress) math.Int); ok {
		r0 = rf(ctx, hashId, payer)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, types.AccAddress) error); ok {
		r1 = rf(ctx, hashId, payer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FeefromReporterStake provides a mock function with given fields: ctx, reporterAddr, amt, hashId, isFirstRound
func (_m *ReporterKeeper) FeefromReporterStake(ctx context.Context, reporterAddr types.AccAddress, amt math.Int, hashId []byte, isFirstRound bool) error {
	ret := _m.Called(ctx, reporterAddr, amt, hashId, isFirstRound)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, math.Int, []byte, bool) error); ok {
		r0 = rf(ctx, reporterAddr, amt, hashId, isFirstRound)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDelegatorTokensAtBlock provides a mock function with given fields: ctx, delegator, blockNumber
func (_m *ReporterKeeper) GetDelegatorTokensAtBlock(ctx context.Context, delegator []byte, blockNumber uint64) (math.Int, error) {
	ret := _m.Called(ctx, delegator, blockNumber)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint64) (math.Int, error)); ok {
		return rf(ctx, delegator, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint64) math.Int); ok {
		r0 = rf(ctx, delegator, blockNumber)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint64) error); ok {
		r1 = rf(ctx, delegator, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDelegatorTokensFromReporterAtBlock provides a mock function with given fields: ctx, delegator, reporter, blockNumber
func (_m *ReporterKeeper) GetDelegatorTokensFromReporterAtBlock(ctx context.Context, delegator []byte, reporter []byte, blockNumber uint64) (math.Int, error) {
	ret := _m.Called(ctx, delegator, reporter, blockNumber)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint64) (math.Int, error)); ok {
		return rf(ctx, delegator, reporter, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, []byte, uint64) math.Int); ok {
		r0 = rf(ctx, delegator, reporter, blockNumber)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, []byte, uint64) error); ok {
		r1 = rf(ctx, delegator, reporter, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReporterTokensAtBlock provides a mock function with given fields: ctx, reporter, blockNumber
func (_m *ReporterKeeper) GetReporterTokensAtBlock(ctx context.Context, reporter []byte, blockNumber uint64) (math.Int, error) {
	ret := _m.Called(ctx, reporter, blockNumber)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint64) (math.Int, error)); ok {
		return rf(ctx, reporter, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, uint64) math.Int); ok {
		r0 = rf(ctx, reporter, blockNumber)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, uint64) error); ok {
		r1 = rf(ctx, reporter, blockNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSelectorForStake provides a mock function with given fields: ctx, selectorAddr
func (_m *ReporterKeeper) GetSelectorForStake(ctx context.Context, selectorAddr types.AccAddress) (reportertypes.Selection, error) {
	ret := _m.Called(ctx, selectorAddr)

	var r0 reportertypes.Selection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) (reportertypes.Selection, error)); ok {
		return rf(ctx, selectorAddr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress) reportertypes.Selection); ok {
		r0 = rf(ctx, selectorAddr)
	} else {
		r0 = ret.Get(0).(reportertypes.Selection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AccAddress) error); ok {
		r1 = rf(ctx, selectorAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JailReporter provides a mock function with given fields: ctx, reporterAddr, jailDuration, reportBlockNumber, disputeHashID
func (_m *ReporterKeeper) JailReporter(ctx context.Context, reporterAddr types.AccAddress, jailDuration uint64, reportBlockNumber uint64, disputeHashID []byte) error {
	ret := _m.Called(ctx, reporterAddr, jailDuration, reportBlockNumber, disputeHashID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, uint64, uint64, []byte) error); ok {
		r0 = rf(ctx, reporterAddr, jailDuration, reportBlockNumber, disputeHashID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReturnSlashedTokens provides a mock function with given fields: ctx, hashId, extraReturn
func (_m *ReporterKeeper) ReturnSlashedTokens(ctx context.Context, hashId []byte, extraReturn math.Int) (math.Int, math.Int, error) {
	ret := _m.Called(ctx, hashId, extraReturn)

	var r0 math.Int
	var r1 math.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, math.Int) (math.Int, math.Int, error)); ok {
		return rf(ctx, hashId, extraReturn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, math.Int) math.Int); ok {
		r0 = rf(ctx, hashId, extraReturn)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, math.Int) math.Int); ok {
		r1 = rf(ctx, hashId, extraReturn)
	} else {
		r1 = ret.Get(1).(math.Int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []byte, math.Int) error); ok {
		r2 = rf(ctx, hashId, extraReturn)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TotalReporterPower provides a mock function with given fields: ctx
func (_m *ReporterKeeper) TotalReporterPower(ctx context.Context) (math.Int, error) {
	ret := _m.Called(ctx)

	var r0 math.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (math.Int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) math.Int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(math.Int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateJailedUntilOnFailedDispute provides a mock function with given fields: ctx, reporterAddr, reportBlockNumber, disputeHashID
func (_m *ReporterKeeper) UpdateJailedUntilOnFailedDispute(ctx context.Context, reporterAddr types.AccAddress, reportBlockNumber uint64, disputeHashID []byte) error {
	ret := _m.Called(ctx, reporterAddr, reportBlockNumber, disputeHashID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AccAddress, uint64, []byte) error); ok {
		r0 = rf(ctx, reporterAddr, reportBlockNumber, disputeHashID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewReporterKeeper interface {
	mock.TestingT
	Cleanup(func())
}

// NewReporterKeeper creates a new instance of ReporterKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReporterKeeper(t mockConstructorTestingTNewReporterKeeper) *ReporterKeeper {
	mock := &ReporterKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
