// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layer/oracle/cross_chain_escrow.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CrossChainFunder is one Layer-side funder of an Ethereum escrow tip.
type CrossChainFunder struct {
	// 20-byte Ethereum address to repay on the escrow chain
	EthPayoutAddress []byte `protobuf:"bytes,1,opt,name=eth_payout_address,json=ethPayoutAddress,proto3" json:"eth_payout_address,omitempty"`
	// gross amount of loya the funder tipped on Layer (pre-burn)
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *CrossChainFunder) Reset()         { *m = CrossChainFunder{} }
func (m *CrossChainFunder) String() string { return proto.CompactTextString(m) }
func (*CrossChainFunder) ProtoMessage()    {}
func (*CrossChainFunder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e416ac1c59b10a4, []int{0}
}
func (m *CrossChainFunder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CrossChainFunder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CrossChainFunder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CrossChainFunder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainFunder.Merge(m, src)
}
func (m *CrossChainFunder) XXX_Size() int {
	return m.Size()
}
func (m *CrossChainFunder) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainFunder.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainFunder proto.InternalMessageInfo

func (m *CrossChainFunder) GetEthPayoutAddress() []byte {
	if m != nil {
		return m.EthPayoutAddress
	}
	return nil
}

// CrossChainEscrow tracks an Ethereum-side tip escrow being fronted on Layer.
type CrossChainEscrow struct {
	// queryId (keccak256 of query_data) the escrow pays for
	QueryId []byte `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// EVM chain id of the escrow contract
	EscrowChainId uint64 `protobuf:"varint,2,opt,name=escrow_chain_id,json=escrowChainId,proto3" json:"escrow_chain_id,omitempty"`
	// 20-byte escrow contract address
	EscrowContract []byte `protobuf:"bytes,3,opt,name=escrow_contract,json=escrowContract,proto3" json:"escrow_contract,omitempty"`
	// escrow id (nonce) inside the escrow contract
	EscrowId uint64 `protobuf:"varint,4,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	// total escrow amount in loya declared by the first funder; funding cap
	DeclaredTotal cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=declared_total,json=declaredTotal,proto3,customtype=cosmossdk.io/math.Int" json:"declared_total"`
	// funders in tip order (first funder first)
	Funders []CrossChainFunder `protobuf:"bytes,6,rep,name=funders,proto3" json:"funders"`
	// true once a settlement aggregate has been produced
	Settled bool `protobuf:"varint,7,opt,name=settled,proto3" json:"settled,omitempty"`
	// block time (unix ms) of the settlement aggregate, 0 if unsettled
	SettlementTimestamp uint64 `protobuf:"varint,8,opt,name=settlement_timestamp,json=settlementTimestamp,proto3" json:"settlement_timestamp,omitempty"`
}

func (m *CrossChainEscrow) Reset()         { *m = CrossChainEscrow{} }
func (m *CrossChainEscrow) String() string { return proto.CompactTextString(m) }
func (*CrossChainEscrow) ProtoMessage()    {}
func (*CrossChainEscrow) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e416ac1c59b10a4, []int{1}
}
func (m *CrossChainEscrow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CrossChainEscrow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CrossChainEscrow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CrossChainEscrow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossChainEscrow.Merge(m, src)
}
func (m *CrossChainEscrow) XXX_Size() int {
	return m.Size()
}
func (m *CrossChainEscrow) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossChainEscrow.DiscardUnknown(m)
}

var xxx_messageInfo_CrossChainEscrow proto.InternalMessageInfo

func (m *CrossChainEscrow) GetQueryId() []byte {
	if m != nil {
		return m.QueryId
	}
	return nil
}

func (m *CrossChainEscrow) GetEscrowChainId() uint64 {
	if m != nil {
		return m.EscrowChainId
	}
	return 0
}

func (m *CrossChainEscrow) GetEscrowContract() []byte {
	if m != nil {
		return m.EscrowContract
	}
	return nil
}

func (m *CrossChainEscrow) GetEscrowId() uint64 {
	if m != nil {
		return m.EscrowId
	}
	return 0
}

func (m *CrossChainEscrow) GetFunders() []CrossChainFunder {
	if m != nil {
		return m.Funders
	}
	return nil
}

func (m *CrossChainEscrow) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

func (m *CrossChainEscrow) GetSettlementTimestamp() uint64 {
	if m != nil {
		return m.SettlementTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*CrossChainFunder)(nil), "layer.oracle.CrossChainFunder")
	proto.RegisterType((*CrossChainEscrow)(nil), "layer.oracle.CrossChainEscrow")
}

func init() {
	proto.RegisterFile("layer/oracle/cross_chain_escrow.proto", fileDescriptor_1e416ac1c59b10a4)
}

var fileDescriptor_1e416ac1c59b10a4 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xdb, 0x90, 0xa4, 0x4b, 0x5b, 0xaa, 0xa5, 0x48, 0xdb, 0x22, 0xb9, 0x51, 0x25, 0x20,
	0x08, 0x6a, 0x0b, 0xb8, 0x23, 0x91, 0x08, 0x24, 0xdf, 0x90, 0xd5, 0x13, 0x17, 0x6b, 0xeb, 0x1d,
	0x62, 0x0b, 0xdb, 0x13, 0x76, 0xc7, 0x82, 0x7c, 0x00, 0x77, 0x3e, 0x86, 0x8f, 0xe8, 0xb1, 0xe2,
	0x84, 0x38, 0x54, 0x28, 0xf9, 0x0d, 0x0e, 0xc8, 0xbb, 0xb6, 0x1a, 0x71, 0xeb, 0x6d, 0xe7, 0xbd,
	0xb7, 0xef, 0xed, 0xcc, 0x0e, 0x7b, 0x54, 0xc8, 0x25, 0xe8, 0x10, 0xb5, 0x4c, 0x0b, 0x08, 0x53,
	0x8d, 0xc6, 0x24, 0x69, 0x26, 0xf3, 0x2a, 0x01, 0x93, 0x6a, 0xfc, 0x12, 0x2c, 0x34, 0x12, 0xf2,
	0x5d, 0x2b, 0x0b, 0x9c, 0xec, 0xf8, 0x28, 0x45, 0x53, 0xa2, 0x49, 0x2c, 0x17, 0xba, 0xc2, 0x09,
	0x8f, 0x0f, 0xe7, 0x38, 0x47, 0x87, 0x37, 0x27, 0x87, 0x9e, 0x7e, 0xf3, 0xd8, 0xc1, 0xac, 0xf1,
	0x9e, 0x35, 0xd6, 0xef, 0xea, 0x4a, 0x81, 0xe6, 0xcf, 0x19, 0x07, 0xca, 0x92, 0x85, 0x5c, 0x62,
	0x4d, 0x89, 0x54, 0x4a, 0x83, 0x31, 0xc2, 0x1b, 0x7b, 0x93, 0xdd, 0xf8, 0x00, 0x28, 0x7b, 0x6f,
	0x89, 0x37, 0x0e, 0xe7, 0x33, 0x36, 0x90, 0x25, 0xd6, 0x15, 0x89, 0xad, 0xb1, 0x37, 0xd9, 0x99,
	0x3e, 0xbb, 0xbc, 0x3e, 0xe9, 0xfd, 0xbe, 0x3e, 0x79, 0xe0, 0xe2, 0x8d, 0xfa, 0x14, 0xe4, 0x18,
	0x96, 0x92, 0xb2, 0x20, 0xaa, 0xe8, 0xe7, 0x8f, 0x33, 0xd6, 0xbe, 0x2b, 0xaa, 0x28, 0x6e, 0xaf,
	0x9e, 0xfe, 0xdd, 0xda, 0x7c, 0xc7, 0x5b, 0xdb, 0x21, 0x3f, 0x62, 0xa3, 0xcf, 0x35, 0xe8, 0x65,
	0x92, 0xab, 0x36, 0x7d, 0x68, 0xeb, 0x48, 0xf1, 0xc7, 0xec, 0x9e, 0x1b, 0x43, 0x3b, 0x93, 0x5c,
	0xd9, 0xf4, 0x7e, 0xbc, 0xe7, 0x60, 0x6b, 0x13, 0x29, 0xfe, 0xe4, 0x46, 0x87, 0x15, 0x69, 0x99,
	0x92, 0xd8, 0xb6, 0x4e, 0xfb, 0xad, 0xae, 0x45, 0xf9, 0x43, 0xb6, 0xd3, 0x0a, 0x73, 0x25, 0xfa,
	0xd6, 0x6a, 0xe4, 0x80, 0x48, 0xf1, 0x98, 0xed, 0x2b, 0x48, 0x0b, 0xa9, 0x41, 0x25, 0x84, 0x24,
	0x0b, 0x71, 0xe7, 0xf6, 0xad, 0xee, 0x75, 0x16, 0xe7, 0x8d, 0x03, 0x7f, 0xcd, 0x86, 0x1f, 0xed,
	0xb8, 0x8d, 0x18, 0x8c, 0xb7, 0x27, 0x77, 0x5f, 0xfa, 0xc1, 0xe6, 0x57, 0x06, 0xff, 0xff, 0xca,
	0xb4, 0xdf, 0x84, 0xc5, 0xdd, 0x25, 0x2e, 0xd8, 0xd0, 0x00, 0x51, 0x01, 0x4a, 0x0c, 0xc7, 0xde,
	0x64, 0x14, 0x77, 0x25, 0x7f, 0xc1, 0x0e, 0xdd, 0xb1, 0x84, 0x8a, 0x12, 0xca, 0x4b, 0x30, 0x24,
	0xcb, 0x85, 0x18, 0xd9, 0xae, 0xee, 0xdf, 0x70, 0xe7, 0x1d, 0x35, 0x9d, 0x5d, 0xae, 0x7c, 0xef,
	0x6a, 0xe5, 0x7b, 0x7f, 0x56, 0xbe, 0xf7, 0x7d, 0xed, 0xf7, 0xae, 0xd6, 0x7e, 0xef, 0xd7, 0xda,
	0xef, 0x7d, 0x78, 0x3a, 0xcf, 0x29, 0xab, 0x2f, 0x82, 0x14, 0xcb, 0x90, 0xa0, 0x28, 0x50, 0x9f,
	0xe5, 0x18, 0xba, 0xdd, 0xfc, 0xda, 0x6d, 0x27, 0x2d, 0x17, 0x60, 0x2e, 0x06, 0x76, 0xa5, 0x5e,
	0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x6f, 0x7a, 0x34, 0xba, 0x02, 0x00, 0x00,
}

func (m *CrossChainFunder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrossChainFunder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CrossChainFunder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.EthPayoutAddress) > 0 {
		i -= len(m.EthPayoutAddress)
		copy(dAtA[i:], m.EthPayoutAddress)
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(len(m.EthPayoutAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CrossChainEscrow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CrossChainEscrow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CrossChainEscrow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SettlementTimestamp != 0 {
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(m.SettlementTimestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.Settled {
		i--
		if m.Settled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Funders) > 0 {
		for iNdEx := len(m.Funders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCrossChainEscrow(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size := m.DeclaredTotal.Size()
		i -= size
		if _, err := m.DeclaredTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.EscrowId != 0 {
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(m.EscrowId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.EscrowContract) > 0 {
		i -= len(m.EscrowContract)
		copy(dAtA[i:], m.EscrowContract)
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(len(m.EscrowContract)))
		i--
		dAtA[i] = 0x1a
	}
	if m.EscrowChainId != 0 {
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(m.EscrowChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.QueryId) > 0 {
		i -= len(m.QueryId)
		copy(dAtA[i:], m.QueryId)
		i = encodeVarintCrossChainEscrow(dAtA, i, uint64(len(m.QueryId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCrossChainEscrow(dAtA []byte, offset int, v uint64) int {
	offset -= sovCrossChainEscrow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CrossChainFunder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EthPayoutAddress)
	if l > 0 {
		n += 1 + l + sovCrossChainEscrow(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovCrossChainEscrow(uint64(l))
	return n
}

func (m *CrossChainEscrow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.QueryId)
	if l > 0 {
		n += 1 + l + sovCrossChainEscrow(uint64(l))
	}
	if m.EscrowChainId != 0 {
		n += 1 + sovCrossChainEscrow(uint64(m.EscrowChainId))
	}
	l = len(m.EscrowContract)
	if l > 0 {
		n += 1 + l + sovCrossChainEscrow(uint64(l))
	}
	if m.EscrowId != 0 {
		n += 1 + sovCrossChainEscrow(uint64(m.EscrowId))
	}
	l = m.DeclaredTotal.Size()
	n += 1 + l + sovCrossChainEscrow(uint64(l))
	if len(m.Funders) > 0 {
		for _, e := range m.Funders {
			l = e.Size()
			n += 1 + l + sovCrossChainEscrow(uint64(l))
		}
	}
	if m.Settled {
		n += 2
	}
	if m.SettlementTimestamp != 0 {
		n += 1 + sovCrossChainEscrow(uint64(m.SettlementTimestamp))
	}
	return n
}

func sovCrossChainEscrow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCrossChainEscrow(x uint64) (n int) {
	return sovCrossChainEscrow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CrossChainFunder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCrossChainEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrossChainFunder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrossChainFunder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthPayoutAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EthPayoutAddress = append(m.EthPayoutAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.EthPayoutAddress == nil {
				m.EthPayoutAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCrossChainEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CrossChainEscrow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCrossChainEscrow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CrossChainEscrow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CrossChainEscrow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryId = append(m.QueryId[:0], dAtA[iNdEx:postIndex]...)
			if m.QueryId == nil {
				m.QueryId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowChainId", wireType)
			}
			m.EscrowChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscrowChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowContract = append(m.EscrowContract[:0], dAtA[iNdEx:postIndex]...)
			if m.EscrowContract == nil {
				m.EscrowContract = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowId", wireType)
			}
			m.EscrowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EscrowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeclaredTotal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DeclaredTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funders = append(m.Funders, CrossChainFunder{})
			if err := m.Funders[len(m.Funders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Settled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Settled = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementTimestamp", wireType)
			}
			m.SettlementTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettlementTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCrossChainEscrow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCrossChainEscrow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCrossChainEscrow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCrossChainEscrow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCrossChainEscrow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCrossChainEscrow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCrossChainEscrow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCrossChainEscrow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCrossChainEscrow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCrossChainEscrow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCrossChainEscrow = fmt.Errorf("proto: unexpected end of group")
)
