// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: layer/oracle/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MinStakeAmount cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=minStakeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"minStakeAmount" yaml:"min_stake_amount"`
	Offset         time.Duration         `protobuf:"bytes,2,opt,name=offset,proto3,stdduration" json:"offset"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0e3bcb871977fd, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOffset() time.Duration {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "layer.oracle.Params")
}

func init() { proto.RegisterFile("layer/oracle/params.proto", fileDescriptor_ac0e3bcb871977fd) }

var fileDescriptor_ac0e3bcb871977fd = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x3f, 0x4f, 0x3a, 0x31,
	0x1c, 0xc6, 0xaf, 0xbf, 0xfc, 0x42, 0xe2, 0xf9, 0x27, 0x91, 0x68, 0x04, 0x86, 0x1e, 0x61, 0x42,
	0x13, 0xda, 0x44, 0x37, 0x26, 0x45, 0x63, 0xc2, 0x66, 0x70, 0x73, 0x21, 0x05, 0xca, 0xd1, 0x70,
	0xed, 0x97, 0xb4, 0xbd, 0x44, 0xde, 0x85, 0x23, 0xa3, 0xa3, 0xa3, 0x83, 0x2f, 0xc0, 0x91, 0x91,
	0x38, 0x19, 0x07, 0x34, 0x30, 0xb8, 0xfb, 0x0a, 0xcc, 0xb5, 0xc7, 0xe2, 0xd2, 0xf4, 0xf9, 0x3e,
	0x7d, 0xfa, 0x7c, 0xd2, 0x86, 0xe5, 0x84, 0x4d, 0xb9, 0xa6, 0xa0, 0x59, 0x3f, 0xe1, 0x74, 0xc2,
	0x34, 0x93, 0x86, 0x4c, 0x34, 0x58, 0x28, 0xee, 0x38, 0x8b, 0x78, 0xab, 0xb2, 0xcf, 0xa4, 0x50,
	0x40, 0xdd, 0xea, 0x0f, 0x54, 0xca, 0x7d, 0x30, 0x12, 0x4c, 0xd7, 0x29, 0xea, 0x45, 0x6e, 0x1d,
	0xc4, 0x10, 0x83, 0x9f, 0x67, 0xbb, 0x7c, 0x8a, 0x63, 0x80, 0x38, 0xab, 0xc9, 0x54, 0x2f, 0x1d,
	0xd2, 0x41, 0xaa, 0x99, 0x15, 0xa0, 0xbc, 0x5f, 0x7b, 0x45, 0x61, 0xe1, 0xc6, 0x21, 0x14, 0x55,
	0xb8, 0x27, 0x85, 0xba, 0xb5, 0x6c, 0xcc, 0x2f, 0x24, 0xa4, 0xca, 0x96, 0x50, 0x15, 0xd5, 0xb7,
	0x5a, 0xd7, 0xf3, 0x65, 0x14, 0x7c, 0x2c, 0xa3, 0x43, 0x5f, 0x67, 0x06, 0x63, 0x22, 0x80, 0x4a,
	0x66, 0x47, 0xa4, 0xad, 0xec, 0xcf, 0x32, 0x3a, 0x9a, 0x32, 0x99, 0x34, 0x6b, 0x52, 0xa8, 0xae,
	0xc9, 0xd2, 0x5d, 0xe6, 0xe2, 0xb5, 0xb7, 0x97, 0x46, 0x98, 0x23, 0xb6, 0x95, 0xed, 0xfc, 0xb9,
	0xbd, 0x78, 0x1e, 0x16, 0x60, 0x38, 0x34, 0xdc, 0x96, 0xfe, 0x55, 0x51, 0x7d, 0xfb, 0xb4, 0x4c,
	0x3c, 0x2b, 0xd9, 0xb0, 0x92, 0xab, 0x9c, 0xb5, 0xb5, 0x9b, 0x21, 0xcc, 0x3e, 0x23, 0xf4, 0xf4,
	0xfd, 0x7c, 0x82, 0x3a, 0x79, 0xae, 0xf9, 0x7f, 0xf6, 0x18, 0x05, 0xad, 0xcb, 0xf9, 0x0a, 0xa3,
	0xc5, 0x0a, 0xa3, 0xaf, 0x15, 0x46, 0x0f, 0x6b, 0x1c, 0x2c, 0xd6, 0x38, 0x78, 0x5f, 0xe3, 0xe0,
	0xee, 0x38, 0x16, 0x76, 0x94, 0xf6, 0x48, 0x1f, 0x24, 0xb5, 0x3c, 0x49, 0x40, 0x37, 0x04, 0x50,
	0xff, 0xfc, 0xf7, 0x9b, 0x0f, 0xb0, 0xd3, 0x09, 0x37, 0xbd, 0x82, 0x2b, 0x3d, 0xfb, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x8d, 0x01, 0x07, 0x9d, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Offset, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Offset):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	{
		size := m.MinStakeAmount.Size()
		i -= size
		if _, err := m.MinStakeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinStakeAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Offset)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStakeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinStakeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Offset, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
